import { groq } from "next-sanity";

export const siteSettingsQuery = groq`
  *[_type == "siteSettings"][0]{
    clinicName,
    phone1,
    phone2,
    email,
    facebookUrl,
    addressLine,
    addressCity,
    taxId
  }
`;

export const homePageQuery = groq`
  *[_type == "homePage"][0]{
    hero{
      eyebrow,
      title,
      description,
      primaryButtonText,
      secondaryButtonText,
      trustPoints,
      imageAlt,
      image{
        asset->{
          url
        }
      }
    },
    whyChooseUs{
      title,
      description,
      items
    },
    servicesOverview{
      title,
      description,
      moreLabel,
      items
    },
    howItWorks{
      title,
      description,
      items
    },
    reimbursement{
      title,
      description,
      buttonText,
      points,
      imageAlt,
      image{
        asset->{
          url
        }
      }
    },
    faq{
      title,
      description,
      items
    }
  }
`;

export const aboutPageQuery = groq`
  *[_type == "aboutPage"][0]{
    hero{
      title,
      lead,
      description,
      imageAlt,
      image{
        asset->{
          url
        }
      }
    },
    intro{
      title,
      paragraph1,
      paragraph2,
      items
    },
    approach{
      title,
      description,
      items
    },
    patientSupport{
      title,
      description,
      items
    }
  }
`;

export const servicesPageQuery = groq`
  *[_type == "servicesPage"][0]{
    seoTitle,
    seoDescription,
    hero{
      title,
      lead,
      description,
      primaryButtonText,
      secondaryButtonText,
      imageAlt,
      image{
        asset->{
          url
        }
      }
    },
    overview{
      title,
      paragraph1,
      paragraph2,
      paragraph3,
      highlightTitle,
      highlightParagraph1,
      highlightParagraph2,
      moreLabel,
      items
    },
    journey{
      title,
      description,
      items
    },
    benefits{
      title,
      description,
      items
    }
  }
`;

export const hearingTestPageQuery = groq`
  *[_type == "hearingTestPage"][0]{
    seoTitle,
    seoDescription,
    hero{
      title,
      lead,
      description,
      primaryButtonText,
      secondaryButtonText,
      imageAlt,
      image{
        asset->{
          url
        }
      }
    },
    intro{
      title,
      paragraph1,
      paragraph2,
      highlightTitle,
      highlightParagraph1,
      highlightParagraph2
    },
    steps{
      title,
      description,
      items
    },
    when{
      title,
      paragraph1,
      paragraph2,
      items
    }
  }
`;

export const hearingAidFittingPageQuery = groq`
  *[_type == "hearingAidFittingPage"][0]{
    seoTitle,
    seoDescription,
    hero{
      title,
      lead,
      description,
      primaryButtonText,
      secondaryButtonText,
      highlightTitle,
      highlightDescription
    },
    intro{
      title,
      paragraph1,
      paragraph2,
      paragraph3,
      highlightTitle,
      highlightParagraph1,
      highlightParagraph2
    },
    process{
      title,
      description,
      items
    },
    factors{
      title,
      paragraph1,
      paragraph2,
      items
    }
  }
`;

export const hearingAidServicePageQuery = groq`
  *[_type == "hearingAidServicePage"][0]{
    hero{
      title,
      lead,
      description,
      primaryButtonText,
      secondaryButtonText,
      highlightTitle,
      highlightDescription
    },
    intro{
      title,
      paragraph1,
      paragraph2,
      paragraph3,
      highlightTitle,
      highlightParagraph1,
      highlightParagraph2
    },
    scope{
      title,
      paragraph1,
      paragraph2,
      items
    },
    support{
      title,
      paragraph1,
      paragraph2,
      listTitle,
      items
    }
  }
`;

export const homeVisitsPageQuery = groq`
  *[_type == "homeVisitsPage"][0]{
    seoTitle,
    seoDescription,
    hero{
      title,
      lead,
      description,
      primaryButtonText,
      secondaryButtonText,
      highlightTitle,
      highlightDescription
    },
    intro{
      title,
      paragraph1,
      paragraph2,
      paragraph3,
      highlightTitle,
      highlightDescription
    },
    whoFor{
      title,
      items
    },
    scope{
      title,
      items
    }
  }
`;

export const hearingAidsPageQuery = groq`
  *[_type == "hearingAidsPage"][0]{
    seoTitle,
    seoDescription,
    hero{
      title,
      lead,
      description,
      primaryButtonText,
      secondaryButtonText,
      imageAlt,
      image{
        asset->{
          url
        }
      }
    },
    intro{
      title,
      paragraph1,
      paragraph2,
      paragraph3,
      highlightTitle,
      highlightDescription
    },
    benefits{
      title,
      description,
      items
    },
    types{
      title,
      paragraph1,
      paragraph2,
      moreLabel,
      items
    }
  }
`;